name: Android Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  android_ui_test_job:
      runs-on: macos-latest
      steps:
        - name: Run Android UI tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 35
            script: /gradlew connectedDebugAndroidTest

  android_unit_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Android UNIT tests
        uses: actions/checkout@v4
