name: Android UI Tests

on:
  push:
  pull_request:
  
  workflow_dispatch:

jobs:
  android_ui_test_job:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [33, 35]
        target: [default]
    steps:
      - uses: actions/checkout@v4
      - name: Provide emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: 'x86_64'
          profile: Nexus 6
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
